version: '3.9'
services:
  fleet-server:
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    container_name: fleet-server
    ports:
      - 8220:8220
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:8220/api/status | grep -q 'HEALTHY'"]
      retries: 300
      interval: 1s
    environment:
      FLEET_SERVER_ENABLE: "1"
      FLEET_SERVER_POLICY: "${POLICY_ID}"
      FLEET_SERVER_ELASTICSEARCH_HOST: http://host.docker.internal:9200
      FLEET_SERVER_ELASTICSEARCH_USERNAME: "${ES_SUPERUSER_USER:-admin}"
      FLEET_SERVER_ELASTICSEARCH_PASSWORD: "${ES_SUPERUSER_PASS:-changeme}"
      FLEET_SERVER_CERT: /etc/pki/tls/certs/fleet-server.crt
      FLEET_SERVER_CERT_KEY: /etc/pki/tls/private/fleet-server-key.key
      FLEET_URL: https://fleet-server:8220
      FLEET_SERVER_SERVICE_TOKEN: "${SERVICE_TOKEN}"
    volumes:
      - ${VOLUME_FLEETSERVER_CERT}:/etc/pki/tls/certs/fleet-server.crt
      - ${VOLUME_FLEETSERVER_KEY}:/etc/pki/tls/private/fleet-server-key.key