instances:
  - name: elasticsearch
    dns: 
      - elasticsearch
      - localhost
      - host.docker.internal
  - name: fleet-server
    dns:
      - fleet-server
      - localhost
      - host.docker.internal