receivers:    
  otlp:
    protocols:
      grpc:
      http:

processors: 
  # 設定採樣率
  probabilistic_sampler:
    sampling_percentage: 50 # 50%
  # 過濾healthcheck的請求
  tail_sampling:
    policies:
      [
        {
          name: healthcheck-filter,
          type: string_attribute,
          string_attribute: 
            {
              key: http.url, 
              values: ['^.*\/(?:metrics|healthcheck|health)$'], 
              enabled_regex_matching: true, 
              invert_match: true
            }
        }
      ]
  memory_limiter:
    # 檢查的時間，建議1秒
    check_interval: 1s
    # 可用記憶體空間
    limit_mib: 500
    # 可用記憶體空間的最大峰值，不可超過limit的值，建議設為limit的20%
    spike_limit_mib: 100
    # limit_percentage: 10
    # spike_limit_percentage: 2
  batch:

exporters:
  logging:
    loglevel: info 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${ELASTIC_APM_SERVER}"  
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, tail_sampling, memory_limiter, batch]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs: 
      receivers: [otlp]
      exporters: [logging, otlp/elastic]